### ISSUE TITLE
Properly initialize timescaledb before other resources access it

### ISSUE THREAD

**Issue by xin-hedera** [hashgraph/hedera-mirror-node#1439]
**Problem**
hedera-mirror's timescale db init job runs as a helm `post-install` hook and the expectation is other resources will not run until the job is done. However, helm `post-install` hook can't be used for such purpose.

**Solution**
The PR https://github.com/timescale/timescaledb-kubernetes/pull/191 will provide the necessary mechanism to run the tasks in the current timescale db init job as timescaledb post init script.

**Alternatives**

**Additional Context**

**Comment by steven-sheehy** [comment]
Note that https://github.com/timescale/timescaledb-kubernetes/pull/191 is only applicable to the `timescaledb-single` chart whereas we are currently using the `timescaledb-multinode` chart. Since that chart and the distributed hypertable functionality in general is still pretty unstable, to address this ticket we should switch to `timescaledb-single` and use the new `postInit` functionality.
