### ISSUE TITLE
Repo cleanup - remove scripts, unused test data

### ISSUE THREAD

**Issue by mike-burrage-hedera** [hashgraph/hedera-mirror-node#185]
Remove some repo files that aren't part of the normal test process or are user settings:

- ~.code-workspace files~ (these are needed)
- /events-0.0.3
- /postgres
- /NodeCollector (unless this is important)

Cleanup .gitignore with related files grouped (such as /config/...)

**Comment by calvinchengx** [comment]
`.code-workspace` files should just be part of the git repository because it's troublesome for each user/developer to have to create exactly the same `.code-workspace` file when using visual studio code.

This workspace file is completely user-agnostic.  And without this file, when a vscode developer opens up the project for the first time, all the Java class paths will not be loaded correctly.

```
# hedera-mirror-node.code-workspace
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"java.configuration.updateBuildConfiguration": "automatic"
	}
}
```

**Comment by steven-sheehy** [comment]
On the flip side, we should be consolidating on a single IDE to use with mirror node. The engineering team mandates Intellij IDEA while me and Mike are using that as well. We should do so as well so everyone is using the same tools and we can check in code styles to ensure the code is formatted consistently.
