### ISSUE TITLE
Error found When running Mirror-node-beta on docker-contianer

### ISSUE THREAD

**Issue by designOm** [hashgraph/hedera-mirror-node#2107]
omprakash_s@taskbarmvp-mirror-node:~/hedera-mirror-node$ docker-compose -v
docker-compose version 1.25.5, build unknown
omprakash_s@taskbarmvp-mirror-node:~/hedera-mirror-node$ docker -v
Docker version 19.03.13, build cd8016b6bc
omprakash_s@taskbarmvp-mirror-node:~/hedera-mirror-node$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.grpc: 'pull_policy'
Unsupported config option for services.importer: 'pull_policy'
Unsupported config option for services.monitor: 'pull_policy'
Unsupported config option for services.rest: 'pull_policy'
Unsupported config option for services.rosetta: 'pull_policy'
omprakash_s@taskbarmvp-mirror-node:~/hedera-mirror-node$

**Comment by steven-sheehy** [comment]
We recently changed the compose file to require Compose file format 3.7 since we require support for the `pull_policy` property. Unfortunately, Docker doesn't provide documentation on which docker-compose binary supports which compose file formats. I would suggest you update to the latest Docker Desktop to solve your issue. I'm using docker-compose v1.29.1 and it works.

**Comment by steven-sheehy** [comment]
Closing this due to no feedback. Let us know if you still have an issue after upgrading Docker Desktop.
