### ISSUE TITLE
YugabyteDB POC

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#2307]
### Problem

Vanilla PostgreSQL can't scale to tens of terabytes. We need to explore distributed databases that can scale to meet mirror node's needs.

### Solution

- [ ] Research the database to ensure it would be a good fit and meets the evaluation criteria
- [ ] Hack the v2 schema to make it work worth with the new db
- [ ] Ensure tests pass locally
- [ ] Run a single node db locally
- [ ] Migrate local demo or integration data to local db
- [ ] Ensure importer and APIs functionally work against it
- [ ] Run a SaaS DB and import mainnet data
- [ ] Ensure 10K ingest performance
- [ ] Ensure API performance

**Comment by ijungmann** [comment]
Summary of POC:

Fits most requirements.  Highly available, Helm chart, SAAS solution with automatic upgrade, partitioning (time-based or otherwise), has some form of compression

Mostly SQL compatible.  Does not support creating a primary key after creating the table.  Does not currently support copying data from temp table to existing tables.  Does not support DDLs inside of user-initiated transactions (including inside Flyway).  Does not support notify.

Importer performance is lacking, and their support for COPY as we currently use it is very fragile, it will disconnect/time out without rolling back, leaving partial file data.  The handling of transactions in general is very spotty.  Even with parallel inserts the performance could only get up to about 2k TPS before major issues started popping up.

Read performance was not tested heavily due to the focus on the importer side, but hitting `/transactions`, the performance was not great, but acceptable.  Bottlenecks seemed to occur on SORT (mostly because of how they create indexes), which could be improved with some work.

Speaking directly with Yugabyte, their biggest success metrics: Plume running at about 312K TPS with 35 TB of data, seeing single-digit latencies.  However, I have not been able to replicate anything even close to those numbers thus far with a pretty strong cluster going.

Overall, Yugabyte was easy to get off the ground, tests mostly passed with minor adjustments, and it may still be worth investigating if we do need to circle back some day, but with our current setup the performance just isn't there, and without clear ways to drastically improve it, it is not a viable candidate.
