### ISSUE TITLE
Treasury account is not associated with token

### ISSUE THREAD

**Issue by robkainz** [hashgraph/hedera-mirror-node#2356]
### Description

The mirror API for retrieving tokens by account id doesn't appear to work correctly in all cases. Here's an example (testnet) where it fails:  [http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.55224](http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.55224)  This account should have all these tokens associated with it (as can be seen on Dragonglass): 

0.0.476170
0.0.476214
0.0.2060379
0.0.2044142
0.0.2120645
0.0.2120646

but the response from the Hedera testnet mirror only includes 0.0.2060379, with no next links. 

But for this account I get the correct response (so it's not broken in all cases): [http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.72004](http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.72004)

### Steps to reproduce

1. Click this URL: http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.55224
2. Compare the results with the token balances available from Dragonglass: https://testnet.dragonglass.me/hedera/accounts/0.0.55224

### Hedera network

testnet

### Version

public testnet mirror

### Operating system

macOS

**Comment by Nana-EC** [comment]
Hi @robkainz .
Thanks for the ticket, this may be by design. 
I believe the reason you are only seeing the 1 token is because it's the only token that the account is associated with.
The Mirror node `api/v1/tokens?account.id=<accountId>` endpoint will list tokens with which accounts are associated with. If you do a TokenAssociate you'll see the tokens appear that list.

**Comment by Nana-EC** [comment]
Additionally, if you just want to get the balances for that account then the right endpoint would be `http://testnet.mirrornode.hedera.com/api/v1/balances?account.id=0.0.55224`
That list seems to match your expectations I believe.

**Comment by robkainz** [comment]
I see, maybe because the account 0.0.55224 in my example is the treasury account for all but one of those tokens? The only token info that did show up via the query http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.55224 was not a treasury account and when I disassociated it, it no longer is returned as a result. Aren't treasury accounts associated? When I try to disassociate a treasury account, I get the error: ACCOUNT_IS_TREASURY. 

So what I need is a mirror node token info query that will give me all the token metadata (symbols included, but also the public keys for KYC, freeze, admin, total supply etc.) for all tokens associated with an account, including those accounts that are treasuries for those tokens. Dragonglass seems to give me some of this data (but not all). Ideally, I would like to be able to get the token metadata easily from the mirror node in one query for all tokens that an account owns (whether it's a treasury or not). Is this not possible?

**Comment by robkainz** [comment]
I just confirmed while trying to associate token 0.0.1957081 (that does not appear in the results for http://testnet.mirrornode.hedera.com/api/v1/tokens?account.id=0.0.55224 ) that I get the error TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT, so that token is supposed to already be associated to the account. Is it possible the query is just not returning tokens that are associated to the queried account id if that account is its treasury?

**Comment by Nana-EC** [comment]
@robkainz  Yes, you are correct treasury accounts are indeed associated automatically with tokens.
That automatic part seems to be the troublemaker here. We don't get a `TOKENASSOCIATE` transaction from the network and as such the mirror node never actually adds a row for that link since it's implicit.
This is an issue on our end and the reason the query is not returning those treasury account details.
We're looking into this and the best approach for addressing this - this will likely be the main change from this ticket.

Regarding your REST API response ask, you'll have to make multiple calls as you're requesting multiple things - token metadata and balance.
We'd recommend
1. Call `api/v1/tokens/<tokenId>/balances?account.id=<accountId>` get the token balances for all the associated tokenIds
2. For each tokenId call `api/v1/tokens/<tokenId>` to get full token details for each case. Unfortunately, `api/v1/tokens` is designed to have a subset of info and not the full metadata you're looking for.
Hope this helps
