### ISSUE TITLE
Research parallel domain ingestion across multiple connections

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-mirror-node#2677]
### Problem

Currently domain ingestion in the importer is performed sequentially.
This prevents scaling and doesn't capitalize on the fact that not all tables require reconciliation during inserts

### Solution

Concurrently insert into tables across multiple connections

- Group table inserts 
- Within groups allow for parallel ingestion execution

**Comment by xin-hedera** [comment]
PoC result and findings are documented [here](https://www.notion.so/swirldslabs/Parallel-Transaction-ed2e7e800e754bccb33d70b57783db7b)

**Comment by xin-hedera** [comment]
The PoC proves that

- PostgreSQL two phase commit can be utilized to split a unit of work to smaller chunks and run them in parallel with transactional atomicity
- Record file parsing duration sees improvement across the board with different transaction type mixes at 10k TPS, the best seen is 2.05s v.s. 1.45s with 10K token transfers

However, there are outstanding issues / concerns:

- in-house two-phase-commit transaction manager v.s. spring data transaction management (e.g., `@Transactional` annotation, `TransactionSynchronization`, `TransactionalEventListener`, and etc)
- `mirror_importer` role needs to be promoted to be the db owner in order to do `drop table` since postgresql prepared transaction doesn't support temporary tables

In the meantime, PostgreSQL 16 is expected to release with faster pg copy and we want to test if the current single `SqlEntityListener` solution will see lower parse duration thus can still meet the performance requirement with entityTransaction enabled.

As a result, we'll close the ticket and revisit should PostgreSQL 16 pg copy improvement couldn't keep importer parse duration under 2s.
