### ISSUE TITLE
HIP-31 Token transfer expected decimals

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#3049]
### Problem

[HIP-31](https://hips.hedera.com/hip/hip-31) adds expected decimals to token transfers. The mirror node should store this new field.

### Solution

- Add `expected_decimals` int to `token_transfers`
- Convert unsigned integer value to signed integer in importer
- Convert signed integer to unsigned number in REST API response

**Comment by xin-hedera** [comment]
Per offline discussion:

1. Users can get the correct decimals of a fungible token from `/api/v1/tokens/{tokenId}` in case a wrong decimals set in the crypto transfer transaction caused failure.
2. In order to extract and save the expected_decimals set by user, a new table is needed though it doesn't add information to what mirror node already has.

We decide to close the ticket and reconsider if in the future there is a strong use case which requires mirror node to save the info and expose it through the rest api.
