### ISSUE TITLE
Missing assessed_custom_fees field

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-mirror-node#3378]
### Description

The endpoint `/api/v1/transactions` is missing the `assessed_custom_fees` field.
Example:
Transaction:
http://testnet.mirrornode.hedera.com/api/v1/transactions/0.0.28526596-1646397557-558465469
has an `assessed_custom_fees` field.
But the same transaction from `/transactions` has not:
http://testnet.mirrornode.hedera.com/api/v1/transactions?timestamp=lte:1646397569.825052630

### Steps to reproduce

1. Create a token transfer transaction with custom fees.
2. Get the transaction from `/api/v1/transactions/{transactionId}` <it has a `assessed_custom_fees` field>
3. Get the transaction same by filtering `/api/v1/transactions`,
 example: `/api/v1/transactions?account.id={accountId}` <it has not a `assessed_custom_fees` field>

### Additional context

With `assessed_custom_fees`:
![image](https://user-images.githubusercontent.com/101180841/157219983-b2f399a5-8997-4806-a9c8-00651ed0a445.png)

Same transaction without `assessed_custom_fees`:
![image](https://user-images.githubusercontent.com/101180841/157219856-ea1de27a-60ea-4acb-b671-668ecc86bdd7.png)

### Hedera network

testnet

### Version

v1

### Operating system

Linux

**Comment by Nana-EC** [comment]
Hi @se7enarianelabs 
Thanks for opening the issue.

This is a by design feature.
The `api/v1/transactions` endpoint is a heavy use endpoint and for performance reasons we discontinued overloading its responses with too many details, especially those that don't relate to the `transaction` object itself.
It makes more sense when peering into a single transaction to view its metadata related features e.g. `assessed_custom_fees` etc.

However, it seems we added it to our documentation since our OpenAPI spec `Transaction` object is shared between the two.
We'll take an item to update the documentation and resolve this comment.

**Comment by Nana-EC** [comment]
Also for easier reference here's a link to compare the same transaction [Transaction 0.0.28526596-1646397557-558465469](https://testnet.mirrornode.hedera.com/api/v1/transactions?timestamp=gte:1646397569.825052629&timestamp=lte:1646397569.825052630)

**Comment by se7enarianelabs** [comment]
okay, thanks
