### ISSUE TITLE
REST API: could differentiate nonexistent topic id from empty message list

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node#3443]
### Problem

/api/v1/topics/{topicId}/messages returns a empty message list in the following 2 cases:
 - the given topic id does not exist
 - the given topic id exists but has no messages

### Solution

It would be nice, when the topic id does not exist, to return an 404 HTTP status  instead, 
so we know whether to display an empty list or to report an error when the user searches for a topic in HashScan.

**Comment by steven-sheehy** [comment]
We can't make this change. Some mirror node operators run a partial mirror node with a start date past the stream start. In those cases, the topic may not exist since they didn't start in time to store the topic create but they are getting topic messages for it still. We still want to show the messages even when the topic id doesn't exist.

Also, it's a performance concern to do the extra lookup to verify topic ID. I think what you really want is the `/api/v1/topics/{id}` [REST API](https://github.com/hashgraph/hedera-mirror-node/issues/774). That would require a HIP though and depend upon availability to implement.

**Comment by steven-sheehy** [comment]
Thanks, will close this in favor of #774 then.
