### ISSUE TITLE
Save transaction hash in the t_transactions table

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-mirror-node#366]
**Problem**
If I understand the backend system properly each transaction has a unique hash (in addition to the transaction id).  For the system I am working on it would be (very) preferable to have access to the hash in the database.

**Solution**
Add the transaction_hash field to the t_transactions table, when parsing the transaction get the hash from the record and store in the database.

**Alternatives**
I could fork this code and manage it myself, but it would preferred to have it added to the hedera official version.

**Comment by steven-sheehy** [comment]
@carlcherry Thanks for feedback. You're referring to the TransactionRecord.transactionHash in the proto, correct? We'd definitely be open to such a feature. Thinking out loud on how to add it we'd need:

- Flyway SQL migration in `src/main/resources/db/migration` that does an alter table to add the bytea transaction_hash field (nullable since we can't fill in old data)
- Add the new field to the insert statement in `RecordFileLogger`
- Update all the `RecordFileLogger*Test` to check for the new field's existence.
- Optionally expose it on the REST API if you need it there

If this is something you're interested in working on, feel free to assign yourself. Or we can take a look at some time in the future.

**Comment by carlcherry** [comment]
Sure - I can work on it.  I have to do it anyway.  Which branch should I start from - master?

**Comment by steven-sheehy** [comment]
Great, I can assign to you. You can work off the master branch.
