### ISSUE TITLE
Expired transactions missing details

### ISSUE THREAD

**Issue by carlcherry** [hashgraph/hedera-mirror-node#393]
Do expired transactions have detailed transfer information.  When the mirror node processes expired transactions is does not add a transfer for the intended target which means the amount is also missing.  In the example below all we know is that 11340 sent some "unknown" amount to some "unknown" target and a couple of nodes were involved.

Example tx: 0.0.11337-1568583349-720942000

If the raw transaction has the info then it would be nice to have it in the postgres database in the t_cryptotransferlists so we can show the failed transaction and its details to the wallet user. I know it might confuse some people to see the transfers but they should assume any status other than SUCCESS means the transfer did not go through

**Comment by mike-burrage-hedera** [comment]
@carlcherry You're basically looking to find out what the intended transfers were (on any failed crypto transfer transaction), right?

**Comment by carlcherry** [comment]
Correct.

**Comment by carlcherry** [comment]
It appears that some other failed transactions have the content - for example this one had the status of INSUFFICIENT_ACCOUNT_BALANCE but the source, target, and amount are there.  I will assume the transfer did not happen.  So perhaps it is just the expired transactions that don't have the transfers?
0.0.16139-1568444863-154000000

**Comment by mike-burrage-hedera** [comment]
Adding detail.
Transaction ID: 0.0.16139-1568444863-154000000
Consensus timestamp: 1568444880178999000
result: INSUFFICIENT_ACCOUNT_BALANCE
transfers:
  0.0.16139 -500,000,000
  0.0.16139 -880
  0.0.16139 -83458

  0.0.16136 +500,000,000

  0.0.98 +880
  0.0.98 +81692
  0.0.10  +1766

**Comment by carlcherry** [comment]
Just a FYI - these records are coming from the S3 bucket hedera-mainnet-streams.  I am assuming by the name that this is the actual production hedera content but I don't have confirmation on that.

Also - you have suggested this is a bug - what is the bug exactly?  That the transfer is missing from the EXPIRED transaction OR that it is included in the INSUFFICIENT_ACCOUNT_BALANCE transaction?

**Comment by mike-burrage-hedera** [comment]
Sorry, I'll create a separate issue and move this INSUFFICIENT_ACCOUNT_BALANCE issue to that. 

In the INSUFFICIENT_ACCOUNT_BALANCE case the transferList that's being returned on the transfer is incorrect - it lists charges that were not actually applied (which is why it ended up in the mirror-node database).

Your original discussion question about the mirror-node storing the intended crypto transfer in the database is a separate issue.

In that case we'll need to decide how to store that information as well as exposing it via the rest-api. Currently we only store data for actual funds transfers. The mirror-node would need to also store the _intent_ to transfer (at least in the case of errors), and differentiate that data from actual transfers in the database (as well as in the data returned by the rest-api).

Does the above summary cover your original question?

**Comment by mike-burrage-hedera** [comment]
Also, to be clear - if a transfer fails post-consensus, there should definitely be transfers from that sender account to pay for the transaction fees. Separate transfers (to pay for the fees) than the original intended recipient of the cryptotransfer

**Comment by carlcherry** [comment]
Yes - thanks.
The missing information for expired transactions is not as critical - since they expired nothing was transferred.
As for the INSUFFICIENT_ACCOUNT_BALANCE is certainly a concern for us since we are getting inaccurate data which would mess up our balance totals.

**Comment by steven-sheehy** [comment]
This ticket is referring to crypto transfer lists but we've since added non fee transfers to show the original transfers in the request. It does not show failed transfers yet which will be tracked via #1936.
