### ISSUE TITLE
/balances/ end point no longer returns all data and pagination is not present

### ISSUE THREAD

**Issue by Burstall** [hashgraph/hedera-mirror-node#4578]
### Description

https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.316647

now only appears to show a subset and it is not paginated ( "links":{"next":null} )

I could not find release notes to suggest this was intentional; unfortunately, it is a breaking change for some of my workflow. Please advise. 

### Steps to reproduce

compare the token count here: https://mainnet-public.mirrornode.hedera.com/api/v1/balances?account.id=0.0.316647

with parsing them here: https://mainnet-public.mirrornode.hedera.com/api/v1/accounts/0.0.316647/nfts

### Hedera network

mainnet

### Version

?

**Comment by steven-sheehy** [comment]
The balances endpoint never paginated token balances, only the top level account balances list. Nor is it possible to add since it's a list within a list. If the very first account in the list had 10M token associations but 100 accounts were in the list, would the next page be for account 101+ or show 0-100 repeatedly until all token balances for them could be shown 100 at a time?

With [HIP-367](https://hips.hedera.com/hip/hip-367), the number of tokens associated with any account went from 1000 to become unbounded. It would be an attack vector if we allowed all token balances to be returned via the existing balances REST API. So as part of that HIP, we gave notice that `/api/v1/accounts`, `/api/v1/accounts/{id}`, and `/api/v1/balances` would all limit how many tokens are returned in its response. We did not document in any release notes because it was a security concern and could be exploited as a denial of service attack. It looks like the numbers in that HIP are out of date after we did performance testing. It should be 50 for `/api/v1/accounts` and `/api/v1/balances` (so 5000 tokens across all 100 accounts returned) or 1000 for `/api/v1/accounts/{id}`.

We are [actively working on](https://github.com/hashgraph/hedera-mirror-node/pull/4593) a new REST API `/api/v1/accounts/{id}/tokens` that will list all token associations and their balances. Until then, if the number of tokens on your account is still under 1000 you can use `/api/v1/accounts/{id}` to view them.

**Comment by Burstall** [comment]
appreciate the clarification.

hope the work to bring the new REST API goes well so we can regain this functionality on accounts that have > 1,000 tokens associated.
