### ISSUE TITLE
Cannot Query Account Balances in v0.67.1

### ISSUE THREAD

**Issue by gitmewai** [hashgraph/hedera-mirror-node#4763]
### Description

We have been using `balances` API for checking account balances. After we upgraded from `v0.65.0` to `v0.67.1`, we found that the API no longer works the same.

### Steps to reproduce

1. Upgrade hedera-mirror node from `v0.65.0` to `v0.67.1` docker image
2. Perform the command `curl -s 'http://x.x.x.x:5551/api/v1/balances?account.id=0.0.account_id'` and the following is returned now:
```
{"timestamp":null,"balances":[],"links":{"next":null}}
```
3. Perform the command `curl -s 'http://x.x.x.x:5551/api/v1/balances?account.id=0.0.account_id&timestamp=1666855809.983411175'` and the following will be returned instead:
```
{"timestamp":"1666845001.084929000","balances":[{"account":"0.0.account_id","balance":0,"tokens":[]}],"links":{"next":null}}
```

### Hedera network

mainnet

### Version

v0.67.1

### Operating system

Linux

**Comment by steven-sheehy** [comment]
Most likely this is because you have a partial mirror node. That is, you don't have the full history from genesis so you're missing the account/contract create/update transactions that would trigger an `entity` row insertion. Without such a row we can't keep a running counter for the real-time balance.

You can still simulate the old behavior by providing a `timestamp=$now` query parameter so that it pulls the information from the 15 minute account balance source, as you noted. We can attempt to insert entities from the data in the balance file to help out partial mirror nodes but it would result in incorrect/missing data like `created_timestamp` and correctly identifying whether it's a contract or an account.

**Comment by gitmewai** [comment]
Is there any means that we can populate the full transaction history of some accounts that are of our own interest? Once it's done, can we check their account balance without specifying the `timestamp`?

**Comment by steven-sheehy** [comment]
> Is there any means that we can populate the full transaction history of some accounts that are of our own interest? Once it's done, can we check their account balance without specifying the `timestamp`?

@gitmewai True, if you had the full transaction history it would work without a timestamp.

Alternatively, you could insert a dummy row into the `entity` table with the minimal required fields and with deleted = false. Then you can [rerun](https://github.com/hashgraph/hedera-mirror-node/tree/main/docs/importer#initialize-entity-balance) the `InitializeEntityBalanceMigration` and the balance should be accurate again.

**Comment by steven-sheehy** [comment]
To fix for every partial mirror node:

* Create a new repeatable migration that:
  * Inserts a minimal `entity` row for every missing entity in the latest `account_balance` dataset with `deleted=false` and `timestamp_range=[epoch,)` so it's clear it's generated data
  * Inserts a `token_account` row for missing every account/token in the latest `token_balance` dataset with `deleted=false` and `consensus_timestamp=token_balance.consensus_timestamp`
* Bump the `InitializeEntityBalanceMigration` checksum it so reruns
* Bump the `TokenAccountBalanceMigration` checksum it so reruns
* Document partial mirror node limitations and above steps to workaround some of those limitations.
