### ISSUE TITLE
Node information api endpoint

### ISSUE THREAD

**Issue by pathornteng** [hashgraph/hedera-mirror-node#4771]
### Problem

Currently, there is no API that returns information about the mirror node such as version, up-time, latest block on the node, system time, etc. These kinds of information are really useful for mirror node operators.

### Solution

Add a generic endpoint for querying information about the current node such as `/info` that returns `version`, `uptime`, `latest block on the node`, `system time` etc.

**Comment by steven-sheehy** [comment]
I don't think such an endpoint provides value. It doesn't make sense to create an API for mirror node operators since if they're running a node they should already know the answer to these questions via metrics, db access, or external triggers (CI deploy).

* `version` - Can already be seen on our Swagger [endpoint](https://mainnet-public.mirrornode.hedera.com/api/v1/docs/) and, while inefficient, could be retrieved programmatically via xpath.
* `uptime` - Uptime of what? It's a microservice architecture with many instances of each microservice. The REST API, gRPC API, Rosetta API, web3 API, or importer uptime? Importer uptime as in how long the importer process has been up, been processing record files, or processing balance files? True uptime of an API could only be discerned from the client point of view and there's no way for an external client to feed back data into the API.
* `latest block on the node` - Already present at `/api/v1/blocks?limit=1`
* `system time` - The mirror node doesn't care about system time. All data is associated with consensus timestamps that come from consensus nodes. If you're referring to latest consensus timestamp you can get that via `/api/v1/transactions?limit=1`.
