### ISSUE TITLE
Reject subscriptions to topics that don't exist

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#498]
**Detailed Description**
We should not allow requests to topic IDs that do not exist.

**Actual Behavior**
1. Call subscribeTopic with a topic that has not been created
2. Connection is established and waits for messages

**Expected Behavior**
Request would be rejected

**Environment:**
- Java: OpenJDK 11
- OS: Ubuntu 18.04
- Version: v0.5.1

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
The topic may have been created via HAPI and not yet propagated to the mirror node via the recordstreams at the point that a client subscribes.
Also, the mirror node may not have stored in the entities table the topic, but it does exist, in the case where data storage/parsing only started after a certain point in time (the mirror node isn't storing the entire history since genesis).
If the mirror node is going to reject the subscription request for a topic it's not currently aware of, then at least we'll need to note these cases for developers and suggest how to implement around these cases.

**Comment by steven-sheehy** [comment]
Yes, I'm aware but my main concern is not utilizing resources indefinitely for a topic that may never exist. I confirmed with Atul his expectation before opening this.

We can return an appropriate error code and document it.

**Comment by mike-burrage-hedera** [comment]
If the concern is not utilizing resources indefinitely, then close the connection with an error after a reasonable amount of time if the topic has not arrived at the mirror-node.

The tradeoff is:
(a) all implementations that create topics and subscribe in short order need to add additional logic to handle this case, versus,
(b) an incorrectly configured client will overutilize resources - which if they implement this same retry logic they will continually do anyways

**Comment by bugbytesinc** [comment]
Well, I think I may have DOSd the testnet this morning because of this behavior.
