### ISSUE TITLE
Archive verified signature files

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#510]
**Problem**
```console
$ find /var/lib/mirror-node/recordstreams/record0.0.3 -type f -printf '.' | wc -c
2260859
```

There are 2.2+ million record signature files in a single node's directory currently in mainnet. This isn't going to reach any limits of the filesystem any time soon but does make it difficult for other tools like `ls`, `find`, etc to work. It also causes unverified signature files to be intermixed with verified files unlike how we treat rcd and balance files.

We also want to implement #259 in the future to not store files at all and save on disk space, but with the current approach that is not possible.

**Solution**
Once all signatures for a particular file have been verified, we should move the verified signature files to the parsed directory. Additionally the directory structure should contain the year and month. 

**Alternatives**

**Additional Context**

**Comment by apeksharma** [comment]
Since #259 is done, this ticket can do something similar as that one.
In downloader, signature files can be deleted (default)/archived after verification succeeds.
Same as in parser: https://github.com/hashgraph/hedera-mirror-node/blob/master/hedera-mirror-importer/src/main/java/com/hedera/mirror/importer/parser/record/RecordFileParser.java#L268

Rough changes:
- New configuration property `archiveSigFiles` in {Record,Balance}DownloaderProperties. Can be set to true. Default false i.e. delete signature files.
- Add `StreamType.getSignatureArchive()`
- Add `DownloaderProperties.getSignatureArchive` (same as getValidPath())
- Similar utility fn as linked above
```
    public static void moveOrDeleteVerifiedSignatureFile(String fileName, String nodeId, DownloaderProperties dP) {
        if (downloaderProperties.isArchiveSigFiles()) {
            Utility.moveFileToDir(fileName, dP.getSignatureArchive().resolve(nodeId));
        } else {
            Utility.deleteFile(fileName);
        }
    }
```
