### ISSUE TITLE
Use real-time token balance in token balances API

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5196]
### Problem

As a REST API user, I'd like to see my up to date token balance information when querying `/api/v1/tokens/{id}/balances`.

### Solution

* Change `/api/v1/tokens/{id}/balances` to query `token_account.balance` when no timestamp parameter is provided
* Update `docs/rest/README.md` to clarify which tables are actually used for all `token_balance` related endpoints.

**Comment by iron4548** [comment]
I did some tests and it would appear that 

/api/v1/tokens/{tokenid}/balances?account.id={accountid}

Would fetch the previous balance instead of the absolute latest.

The account in question is 0.0.2751778 (which belongs to a DEX smart contract). 

Let's assume that on hashscan.io the current balance for the KARATE token (0.0.2283230) is 12345. 

After I do a swap on this HBAR/KARATE pair (via SaucerSwap), hashscan.io will show the new correct balance: 67890

However when I call the API, it would return the previous token balance (12345). I waited for at least 5 minutes and the API would still return the old balance (12345).

Then interestingly, if I execute another swap on this same pair on SaucerSwap, the balance gets updated but instead of returning the latest (now 99999 via hashscan.io) it would return 67890 (the now previous one)

I did another swap, and same thing happens. It gives me 99999 (now previous) instead of 1111111 (latest)

So it seems to return the last balance instead of the latest, where I'd like to get the latest balance

**Comment by iron4548** [comment]
Some more info:

"I made a small script that would fetch the token balance via REST API every 5 seconds. And I compared this with hashscan.io. There was a mismatch. And it continued to stay different for at least 10 minutes. When I interact with the DEX to force the balances to update, the REST API would return a different balance relevantly soon (less than 10 seconds) but it would show me the previous balance values
I did it again, and same thing happened
and again and again"

**Comment by steven-sheehy** [comment]
All of hashscan's data comes from mirror node APIs. This API `/api/v1/tokens/{id}/balances` still uses the 15 minute balance file as its source. To be clear, `/api/v1/tokens/{id}/balances` is 100% correct and up to date at the timestamp that it returns in its response. Hashscan probably uses `/api/v1/accounts/{id}` to get token balance info, which has a balance accumulated from the record files written every 2 seconds. 

What you see is entirely expected. Once this ticket is implemented, both will update its balance information at the same cadence.
