### ISSUE TITLE
HIP-584: Add revert reason for failing requests in web3 module

### ISSUE THREAD

**Issue by IvanKavaldzhiev** [hashgraph/hedera-mirror-node#5399]
### Problem

Currently when we call `api/v1/contracts/call` under the web3 module and there is a failure in the execution, we return only the error code in the message field of the JSON error response. It looks like this:

```
{
    "_status": {
        "messages": [
            {
                "message": "CONTRACT_REVERT_EXECUTED"
            }
        ]
    }
}
```

Currently on the json-rpc-relay side, failing `eth_call` requests sent to the consensus node return also the detailed revert reason, which is consumed from the relay. It would be useful this revert reason to be also enhanced in the web3 module on mirror-node side.

### Solution

Add additional field `detail` to the json error response body under web3 submodule.

**Comment by steven-sheehy** [comment]
The error message structure is supposed to be the same across all of our Rest APIs. Instead of adding a contract call specific field, let's add a more generically named field that will contain message details. [RFC7807](https://www.rfc-editor.org/rfc/rfc7807#section-3.1) is implemented by Spring 6 and we should use that as inspiration. So let's name the field as `detail` instead of `revertReason`.

**Comment by IvanKavaldzhiev** [comment]
@steven-sheehy Should we stick to the human-readable string format, as noted in the documentation, or we can return the revert reason directly as hex string?

**Comment by steven-sheehy** [comment]
I think it should be the human readable string if it's guaranteed that the revert reason bytes will be human readable, utf-8 encoded data. The relay can convert it to hex to comply with the JSON-RPC spec.

**Comment by steven-sheehy** [comment]
@Kalina-Todorova Why was this reopened? There was a PR that closed this item. Please open a new task if you feel it is not complete and requires follow up actions.
