### ISSUE TITLE
Remove entity deletion check in balance migrations

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#5464]
### Problem

As a partial mirror node operator, I may not have a complete list of entities in the database to be able to pass the deletion check when running the balance migrations.

### Solution

* Change `InitializeEntityBalanceMigration` to remove the join and check for deleted entity
* Change `TokenAccountBalanceMigration` to remove join and check for deleted entity

**Comment by MarcKriguerAtHedera** [comment]
I made the two listed changes above, and ran all tests -- only two broke (the integration tests for exactly those migrations.  In the former, there were 3 tests where the `deletedEntityTokenAccount4` needed tp have its balance set (to a non-zero number) in order to pass, and in the latter, it was 2 tests where `accountDeleted` needed to have its balance set (to 20, in both cases) in order to get the tests to pass.  I think that we may not need to add any new tests (but let me know if you disagree).
