### ISSUE TITLE
Cost and performance estimator

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#557]
**Problem**
We need a way to estimate the costs and performance of the mirror node as time and TPS increase.

**Solution**
Create a spreadsheet in Sharepoint that contrasts cost/performance with time/TPS:

Months | TPS | File Storage Cost | DB Storage Cost | S3 Storage Cost | S3 Egress Cost | 
-|-|-|-|-|-
1 | 10 | $123 | $456 | $789 | $12

- All the costs should be variables that can be adjusted
- Changing TPS or months will adjust the other rows appropriately
- We want to show estimated costs over time hence why both months and TPS in the table (e.g. 1 month at 10TPS + 3 months at 20 TPS etc)
- Totals across all months at the bottom

**Alternatives**

**Additional Context**

**Comment by mike-burrage-hedera** [comment]
For storage, remember that each transaction is stored (permanently) in 56 places (some with additional sigs)
(eventstream + recordstream) * (aws + gcs) * (13 nodes) + (primary mirror + failover) * (main + replica DBs)

**Comment by gregscullard** [comment]
Separate issue, but seeing that most of the 13 nodes' files are duplicates (records and events), could we consider deleting any binary identical files ? Should be able to reduce the number of files from x13 to x1 or thereabouts.

**Comment by gregscullard** [comment]
And you probably need to consider testnet too ?

**Comment by gregscullard** [comment]
And you probably need to consider testnet too ?

**Comment by gregscullard** [comment]
And you probably need to consider testnet too ?

**Comment by steven-sheehy** [comment]
The spreadsheet should be per environment, not absolute costs across environments.

**Comment by mike-burrage-hedera** [comment]
I updated the spreadsheet to include mainnet and testnet on each row (not separate rows - it's the same bill) with TPS and average transaction size for each.

There's a powerpoint with the same name in the same folder attempting to explain.

Estimation is difficult because:
- a large portion of the cost overall is based on how (and how frequently) clients poll the streams - each client is different and we're not sure how many there are and don't have control over how efficiently/inefficiently polling/downloading happens. This includes starting up a new node
- transactions vary widely in both size on the wire and storage required in the mirror DB (HCS potentially being 30 times bigger than transfers but it depends on how big the average HCS transaction is as well)

**Comment by apeksharma** [comment]
If it's not being verified even after a month, it's not P1.
Gonna cut the thread on this one. Feel free to reopen if above spreadsheets doesn't serve the purpose AND someone is actually gonna work on it immediately (so no moving to cold slab).
Btw, looked at it, played with it, looks decent enough to me for now.
