### ISSUE TITLE
Rework address book file update

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-mirror-node#58]
When a transaction to update the address book is detected by mirror node, the address book file is updated.
Need to test this scenario with an actual address book update transaction.

In the event that an address book update transaction itself cannot be tested, a test with another file to verify contents are updated would be a good first confidence test.

1. Create a file on the file system containing some data
2. Create the same file on the network via a transaction
3. Issue an update transaction for the same file with new contents
4. Check that the 0.0.102 file contains the new contents.

**Comment by gregscullard** [comment]
An address book update may come through several transactions due to its size, it may therefore show up as a `fileUpdate` followed by n * `fileAppend`.

The address book file may be updated after the last `fileAppend`, however it won't be known which is the last, so after an append, try to convert the data received to date to an address book protobuf object, if this fails, await additional data.

-Other transactions may happen between update and append.
-The downloader needs the address book to be up to date, the parser takes care of maintaining it.
-The downloader should handle signature verifications gracefully first, try with the new address book (if updated) and fail only if the new address book doesn't validate files
-Alternatives. 
1. Implement a query to get the address book on failure to verify (this has a cost attached and requires private keys to be held as environment variables/config).
2. Download the address book from S3/GCP (subject to it being pushed there by devops)
3. Download the address book from a known http location (subject to it being available there)

**Comment by gregscullard** [comment]
Note: Testing of fileAppend that results in an address book append fails checking the results of the append due to `addressBookBytes` being a static. The size of the updated file cannot be reliably compared to the transaction payload size.

**Comment by steven-sheehy** [comment]
Just to expand on some of the things Greg said, any solution needs to:

- Not write to in memory objects as they are stateful and we may lose data if restarted before it's complete
- Use an addressbook.bin.tmp to store address books that don't fit in a single file update and doesn't parse
- Overwrite addressbook.bin if file update parses
- Overwrite addressbook.bin if contents of tmp file plus file append contents parse
- Otherwise append to addressbook.bin.tmp if file append and it exists
- Delete tmp whenever addressbook.bin written
- Simplify reads to just read from disk, but put a @Cacheable on it
- @CacheEvict any write methods
