### ISSUE TITLE
Bump networkController.js max results to 39

### ISSUE THREAD

**Issue by cweagans** [hashgraph/hedera-mirror-node#6015]
### Problem

It's a really minor problem, but when I was writing a piece of code that needed to query the node list from the mirror node, I was a little frustrated to find that I needed to page through the results of a list that will always be really small.

### Solution

It makes a lot of sense to me to at least bump the max results to 39. Since there will only be 39 nodes, it seems like it would make sense to simply return the entire list in one query -- we're not talking about a huge dataset here.

Bumping https://github.com/hashgraph/hedera-mirror-node/blob/27655f8ddceb7e65df98253c8a8999c824f31c47/hedera-mirror-rest/controllers/networkController.js#LL43C32-L43C32 to 39 would solve my specific problem, but it might also make sense to bump https://github.com/hashgraph/hedera-mirror-node/blob/27655f8ddceb7e65df98253c8a8999c824f31c47/hedera-mirror-rest/controllers/networkController.js#LL42C1-L42C1 to 39. If you do that, the entire response can be cached aggressively + served very quickly. mirror-node-explorer could also just make _one_ request to get the node list + cache the result locally.

https://github.com/hashgraph/hedera-mirror-node/blob/27655f8ddceb7e65df98253c8a8999c824f31c47/hedera-mirror-rest/controllers/networkController.js#L92 leads me to believe that this is not as straightforward as I imagine, but maybe there's some way to allow for a complete node list as long as the caller isn't asking for anything too fancy?

**Comment by steven-sheehy** [comment]
> Since there will only be 39 nodes

That's not the case. Hedera is working on adding community nodes soon as you can see on the [roadmap](https://hedera.com/roadmap). After community nodes, permission-less nodes will be the goal. So there could be hundreds, possibly thousands of nodes at some point. It doesn't make sense to make the limit an arbitrary 39 with that in mind.

Choosing a default of 10 and a limit of 25 for `/api/v1/network/nodes` was intentional and makes sense due to the increased size of data this endpoint returns. Querying for 25 nodes on mainnet returns 42 KiB worth of data. I don't think doing two calls versus one for all council nodes would make much difference for client apps. Our CDN caches this response, but client apps themselves should be heavily caching it as well since nodes rarely change.
