### ISSUE TITLE
Flaky stateproof monitor check

### ISSUE THREAD

**Issue by steven-sheehy** [hashgraph/hedera-mirror-node#6085]
### Description

We get periodic false alerts for our monitor API state proof check. The issues occurs because of a race condition between clusters and cloud bucket delay.

### Steps to reproduce

Run monitor API against mainnet

### Hedera network

mainnet

### Version

v0.80.0

### Operating system

None

**Comment by xin-hedera** [comment]
It turns out there’s regression when upgrading aws js SDK to v3, due to the config changes, the config options httpOptions and maxRetries are not set properly for v3 s3 client. Subsequently, the stateproof rest api may take much longer to complete a request than honoring the timeout, the monitor then would abort the check as it exceeds the default 30s timeout in monitor’s config.

reference: https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md
