### ISSUE TITLE
Transactions [Rest Api Query] to add `exclude` so it returns transactions not included a limited array of account_ids

### ISSUE THREAD

**Issue by daniel-bcw** [hashgraph/hedera-mirror-node#7202]
### Problem

We would like to fetch transactions that do not involve a specific account_id.

Ideally it could be something like adding a parameter like `exclude` with a set of account_ids.
We have tried to solve the problem through adding a combination of `gt` and `lt` but this doesnt work.
https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?account.id=gt:0.0.1693742&account.id=lt:0.0.1693742

### Solution

Augment `/transactions` 

- add  a query parameter `exclude` that a set of account_ids can be added (potentially with a limit configurable in the mirror node default `3`, so community or dedicated mirror nodes can leverage further).

Example
 https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?exclude=0.0.16845,0.0.12456&order=desc

The query returns all latest transactions from which these accounts are not associated with.

### Alternatives

Making the query `lt` & `gt` work so the account_id that is referenced is not included in the transactions.
For example:

https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?account.id=gt:0.0.1693742&account.id=lt:0.0.1693742

(Seems more complex to implement at a first glance)

**Comment by steven-sheehy** [comment]
Basically you want to exclude Atma's topic ID? `0.0.1693742` is a topic ID, not an account ID so it doesn't work with the `account.id` parameter. The `account.id` parameter basically only works for transfers and the payer account. There's another ticket that would allow filtering by arbitrary entity IDs but is not performant enough to enable currently. 

But even if that was implemented, I'm not sure we could support an `exclude` parameter since at 28B rows a `NOT IN` would not be performant to support, especially by itself. At this scale, sers should write their queries to target the specific ID they want instead of trying to list everything and blacklist a few IDs.

**Comment by daniel-bcw** [comment]
Hi Steven, noted thanks for the quick reply, perhaps a middleware handling this sort of edge cases might make more sense. 
(For the 28B rows more extreme case i guess the scenario would still be to limit the transactions by result limit at the db query level , still max 100, but just where those specific id's would not be present? But from what is being said , i guess that will still not mitigate the computational weight of that db query. )

Let me cross check back and see if we can find other alternatives.  Thanks!

**Comment by steven-sheehy** [comment]
Hi @daniel-bcw is it okay to close this now?

**Comment by daniel-bcw** [comment]
Hi Steven,

Yes please do, thanks!

Daniel
