### ISSUE TITLE
Add consensus_ns of first and last transactions in t_record_files

### ISSUE THREAD

**Issue by apeksharma** [hashgraph/hedera-mirror-node#724]
Needed by brd to emulate blocks.

" I create my own table and create a psuedo "block" number from the t_record_files table.  So basically the first file would be block 0.
I do it is a separate process on a regular interval.  Check for new records on the t_record_file table then add them to my table always making sure that the prev_hash matches the hash of the previous record.  Our system requires us to import "blocks" with their associated transactions and transfers.
I can get the file timestamp from the first_consensus_ns (we want a block timestamp in our system).  But I do need the hash values so I can ensure that I am getting the files in the correct order."

**Comment by carlcherry** [comment]
Just for a bit of clarity here - since V1.20__drop_file_id.sql removes the fk_rec_file_id field from t_transactions there would be not way to lookup all the transactions that belong to a specific file.

What I will need long term from the t_record_files table is this:
- file_hash and prev_hash so I can validate that we have all the files and can determine the proper order.
- concensus_ns_start, consensus_ns_end (so I can get all transactions for a file)
- filename - I use the filename to figure out the block time - but I suppose I could use one of the consensus times to calculate instead.
