### ISSUE TITLE
run mirror node on Ubuntu VM instead of GCP/AWS?

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [hashgraph/hedera-mirror-node#7862]
### Problem

Documentation suggests that we cannot run a mirro node without GCP/AWS

For someone who can arrange a VM with a large enough SSD, 32 GB ram, 32 cores CPU - they should be able to run the Mirror Node locally on Ubuntu without requiring cloud service providers like Google Cloud / Amazon

As far as what i have gathered, Mirror nodes simply gather record files from Hedera Consensus nodes and put them in a cloud storage bucket (i.e AWS S3).

### Solution

Add a separate portion to the Hedera Mirror Node Documentation, detail how to run Hedera Mirror node **without** cloud service provider and on your local machine or Ubuntu VM.

Mirror nodes are akin to archive nodes in other DLTs, they simply store transaction data but do not partake in consensus/validation duties of the network - therefore, running them locally should not entail the usage of a cloud service but instead we should be able to also run them on VMs equipped with ample storage resources

**Comment by steven-sheehy** [comment]
> Documentation suggests that we cannot run a mirro node without GCP/AWS

Regardless of deployment approach, this is definitely true since at minimum mirror node requires requester pays credentials for either GCS or S3 to be able to download the stream files. But this is just configuration and we never state that the app requires it to be ran inside Google or Amazon.

We already support running a mirror node on your local machine and have documented the multiple ways of doing so.

* [Helm chart on Kubernetes](https://github.com/hashgraph/hedera-mirror-node/blob/main/charts/README.md)
* [Docker Compose](https://github.com/hashgraph/hedera-mirror-node/tree/main#running)
* [Local Node](https://github.com/hashgraph/hedera-local-node)

That said, each of these use containers. If you are wanting to run on a VM without the use of containers we will not be documenting or recommending such an approach. Also, the latter two while document are not recommended for production usage. We can only recommend using our Helm chart. Please let me know if this sufficiently addresses your question.

**Comment by steven-sheehy** [comment]
> As far as what i have gathered, Mirror nodes simply gather record files from Hedera Consensus nodes and put them in a cloud storage bucket (i.e AWS S3).

You have this backwards. Consensus nodes batch transactions into record files, sign them, and upload them to cloud storage. Mirror node simply downloads them and ingests into its database and serve via an API. See https://docs.hedera.com/hedera/core-concepts/mirror-nodes

**Comment by SyedMuhamadYasir** [comment]
> > As far as what i have gathered, Mirror nodes simply gather record files from Hedera Consensus nodes and put them in a cloud storage bucket (i.e AWS S3).
> 
> You have this backwards. Consensus nodes batch transactions into record files, sign them, and upload them to cloud storage. Mirror node simply downloads them and ingests into its database and serve via an API. See https://docs.hedera.com/hedera/core-concepts/mirror-nodes

Thank your for clarifying - this is all very interesting and quite different from most other DLTs.

I would like to summaris what i learned from my discussion with you and make sure i understand the Hedera system correctly.

say we want to primarily run an Archive Node (Mirror Node, in Hedera lingo, i presume) for research purposes - so we will not become a validator ( at least not in the near future ) and we will probably not deploy any high stakes app that will be paid for by irl money. 

In such a case, i am assuming it will be safe to run a hedera mainnet mirror node, through docker compose/ containers ?

but still, even then i cannot maintain a hedera archive node without access to the cloud service ?

i guess it comes down to downloading record files from the data buckets, which incurs the monetary charges - which must be paid for by the requester - in the form of a cloud subscription ( i.e GCP/AWS)

if there is a way for me - to obtain the record files, without purchasing a cloud service subscription, please do let me know.

Your insights and advice are both highly regarded!

**Comment by steven-sheehy** [comment]
> if there is a way for me - to obtain the record files, without purchasing a cloud service subscription, please do let me know.

No, I've already answered this: `at minimum mirror node requires requester pays credentials for either GCS or S3 to be able to download the stream files`.

**Comment by steven-sheehy** [comment]
Closing since this isn't an actionable issue.
