### ISSUE TITLE
Add labels to all hedera-mirror-monitor metrics

### ISSUE THREAD

**Issue by shezaan-hashgraph** [hashgraph/hedera-mirror-node#8874]
### Problem

The DevOps team would like to request the following labels and their corresponding values to all hedera-mirror-monitor metrics as we consider them standardized metrics that we can use in Prometheus for grouping purposes.

1. `network` - Name of the network e.g. testnet, mainnet, previewnet, other
2. `node_id` - Node IDs are not the same as account IDs e.g. `node_id: 0` corresponds to `account_id: 0.0.3` or `account_id: 3`
3. `proxy_ip`: This is the IP address of the proxy

### Solution

Export metrics for hedera-mirror-monitor

1. `network` - Name of the network e.g. testnet, mainnet, previewnet, other
2. `node_id` - Node IDs are not the same as account IDs e.g. `node_id: 0` corresponds to `account_id: 0.0.3` or `account_id: 3`
3. `proxy_ip`: This is the IP address of the proxy

**Comment by steven-sheehy** [comment]
Network can be added to all metrics multiple ways. You can add it yourself to all metrics by adding it to the extraLabels in the Prometheus remote write configuration. We can add it manually to each metric, but this wouldn't add it to non `hedera_` metrics. We can set `management.metrics.tags.network=${hedera.mirror.monitor.network}` via config, but it's a bit redundant for us since we already have namespace which is named after the network. You can try setting that property yourselves.

For the others, it's doable but would take some rework of the internals. Currently we're not passing the node info to the metrics layer. We're just extracting the list of node account IDs from the SDK `Transaction` in the metrics layer. It's something we can explore.
